---
name: Release hashicorp.terraform

on:   # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Automation Hub release
    environment: "${{ inputs.environment }}"
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat README.md
  release_automation_hub:
    uses: NilashishC/ansible-content-actions/.github/workflows/release_ah.yaml@update_release_ah
    with:
      environment: ah
    secrets:
      ah_token: abcd
